Repository sarugaku/requirementslib, pull requests merged in 2018-08, with the labels that each got.

#41 Add extras for the constraint line for VCS
  src/requirementslib/models/requirements.py
  tests/unit/test_requirements.py
Labels: backlog

#46 Do not include hash when geenrating line for ireq
  news/45.bugfix.rst
  src/requirementslib/models/requirements.py
Labels: bug, in progress, input parsing, review

#47 Add commit hash locking
  news/47.feature
  src/requirementslib/models/requirements.py
  src/requirementslib/models/vcs.py
  tests/unit/test_dependencies.py
  tests/unit/test_requirements.py
  tests/unit/test_utils.py
Labels: enhancement, vcs

#51 Optimize lockfile load times
  docs/requirementslib.requirements.rst
  news/51.feature
  src/requirementslib/models/lockfile.py
  tests/unit/strategies.py
  tests/unit/test_lockfile.py
Labels: in progress, review

#53 Fix VCS file uri requirement parsing
  news/53.bugfix
  src/requirementslib/models/pipfile.py
  src/requirementslib/models/requirements.py
Labels: review
